### DISCUSSION TITLE
Errors on Example Scripts

### DISCUSSION THREAD

**Discussion by ghost** [surgical-robotics-ai/surgical_robotics_challenge#19] [Q&A] [answered]
Hi,

I was facing few errors on the example scripts and wanted to clarify if I was doing something wrong.

In the script project_needle_pts.py,  

I get the following error:
```
cv2.imshow("img", img)
cv2.error: OpenCV(4.2.0) ../modules/highgui/src/window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in > function 'imshow'
```
This is because the camere frame L returns a None image. I am not sure how to fix this

In the script, launch_crtk_interface.py 

```
[*]using existing path at .
Specified Arguments
Namespace(namespace='/CRTK', rate=120, run_ecm=True, run_psm_one=True, run_psm_three=False, run_psm_two=True, run_scene=True)
Found Common Object Namespace as:  /ambf/env/
Launching CRTK-ROS Interface for PSM1 
psm1_target_ik NAMED OBJECT NOT FOUND
psm1_palm_joint_ik NAMED OBJECT NOT FOUND
psm1_target_fk NAMED OBJECT NOT FOUND
[ 5. -5. -2.  2. -5. -5.]
Launching CRTK-ROS Interface for PSM2 
psm2_target_ik NAMED OBJECT NOT FOUND
psm2_palm_joint_ik NAMED OBJECT NOT FOUND
psm2_target_fk NAMED OBJECT NOT FOUND
[-5. -5.  5. -5. -2. -5.]
Launching CRTK-ROS Interface for ECM 
Launching CRTK-ROS Interface for Scene 
ERROR! Requested Joint Idx of "0" outside valid range [0 - -1]
ERROR! Requested Joint Idx of "1" outside valid range [0 - -1]
ERROR! Requested Joint Idx of "2" outside valid range [0 - -1]
ERROR! Requested Joint Idx of "3" outside valid range [0 - -1]
ERROR! Requested Joint Idx of "4" outside valid range [0 - -1]
ERROR! Requested Joint Idx of "5" outside valid range [0 - -1]
Traceback (most recent call last):
  File "launch_crtk_interface.py", line 376, in <module>
    sceneManager.run()
  File "launch_crtk_interface.py", line 347, in run
    comp.run()
  File "launch_crtk_interface.py", line 164, in run
    self.publish_js()
  File "launch_crtk_interface.py", line 151, in publish_js
    self._measured_js_msg.position = self.arm.measured_jp()
  File "/home/haaris/surgical_robotics_challenge/scripts/surgical_robotics_challenge/psm_arm.py", line 213, in measured_jp
    q = self._joint_error_model.remove_from_joints(q, self._joints_error_mask)
  File "/home/haaris/surgical_robotics_challenge/scripts/surgical_robotics_challenge/utils/joint_errors_model.py", line 83, in remove_from_joints
    q[i] = q[i] - self.joint_erros_rad[i]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Closing publisher for:  /ambf/env/Plane
Closing publisher for:  /ambf/env/lights/light2
Closing publisher for:  /ambf/env/cameras/cameraL
Closing publisher for:  /ambf/env/cameras/cameraR
Closing publisher for:  World
Closing publisher for:  /ambf/env/psm1/baselink
Closing publisher for:  /ambf/env/psm1/toolyawlink
Closing publisher for:  /ambf/env/psm1/Sensor0
Closing publisher for:  /ambf/env/psm1/Actuator0
Closing publisher for:  /ambf/env/psm2/baselink
Closing publisher for:  /ambf/env/psm2/toolyawlink
Closing publisher for:  /ambf/env/psm2/Sensor0
Closing publisher for:  /ambf/env/psm2/Actuator0
Closing publisher for:  /ambf/env/BlackGround
Closing publisher for:  /ambf/env/CameraFrame
Closing publisher for:  /ambf/env/Ledge
Closing publisher for:  /ambf/env/Needle
Closing publisher for:  /ambf/env/Phantom
Closing publisher for:  /ambf/env/Barrier
Closing publisher for:  /ambf/env/Entry1
Closing publisher for:  /ambf/env/Entry2
Closing publisher for:  /ambf/env/Entry3
Closing publisher for:  /ambf/env/Entry4
Closing publisher for:  /ambf/env/Exit1
Closing publisher for:  /ambf/env/Exit2
Closing publisher for:  /ambf/env/Exit3
Closing publisher for:  /ambf/env/Exit4
```
I wanted to know if the "NAMED OBJECT NOT FOUND" is an issue on my end.

Thank you

**Comment by adnanmunawar** [comment, marked as answer]
Hi Haris, thanks for posting your question. It appears that you may be encountering two different issues. For the first one, regarding the "None" image from cameraL, did you follow the instructions discussed in the main readme [section 3b](https://github.com/collaborative-robotics/surgical_robotics_challenge#3b-simulated-cameras) that enable camera image publishing?

Regarding the second issue, thanks for posting the console output, let me check what is going on and I shall get back to you.

**Reply by ghost** [reply]
Yes, I enabled publish image and depth.

**Reply by adnanmunawar** [reply]
Great thanks, so to answer your earlier question:
>I wanted to know if the "NAMED OBJECT NOT FOUND" is an issue on my end.

No those are just warnings, they are normal.

Now, regarding the problems:

Can you try a couple of things and post the output. 
First:
Please run the `surgical_robotics_challenge` scene as described in the main Readme and then in a new terminal.

Can you run `rostopic hz /ambf/env/cameras/cameraL/ImageData` and show the output. You already mentioned that there is no image but let's double-check. If you get 'no new messages', please verify that you have the two packages mentioned [here](https://github.com/WPI-AIM/ambf/wiki/Camera-feed-and-depth-camera) installed and then you must rebuild AMBF before relaunching the surgical robotics scene.

Second:
With the `surgical_robotics_challenge scene` running, and after the `launch_crtk_interface.py` runs and fails.
Can you run `rostopic echo /ambf/env/psm1/baselink/State` and post the output from a few secs.

**Reply by ghost** [reply]
Hi,

For the first one, the warning appears when I run the command. After running project_needle_pts.py and it throws the assertion error, I get infinite no new messages
```
WARNING: topic [/ambf/env/cameras/cameraL/ImageData] does not appear to be published yet.
```
```
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
```
For the second one, it did not crash this time. Also, I did not update to the latest commit that you added. Maybe it was a one off thing. I added the output anyway.
```
joint_positions: [0.9393907785415649, -0.8615643382072449, -5.456075541587779e-06, -1.9669311046600342, -1.5729533433914185, -0.007319242227822542, 0.4990171790122986, 0.49937185645103455]
joint_velocities: [1.3965414837002754e-05, 2.0841331206611358e-05, -1.0774289238568713e-09, 0.0005466574802994728, 3.5439118306612727e-09, 1.0505500540602952e-05, 5.980509421021907e-09, -4.6486935190159784e-08]
joint_efforts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 40794
  stamp: 
    secs: 1645168990
    nsecs: 270056248
  frame_id: ''
sim_step: 56649
name: 
  data: "baselink"
wall_time: 472.1136474609375
sim_time: 472.07501220703125
mass: 0.0
pInertia: 
  x: 0.0
  y: 0.0
  z: 0.0
pose: 
  position: 
    x: 0.9999999999999999
    y: 1.3461
    z: 1.3499
  orientation: 
    x: -0.24321186724195806
    y: -0.33035197102490294
    z: -0.9076783411704369
    w: 0.08851887845389675
twist: 
  linear: 
    x: 0.0
    y: 0.0
    z: 0.0
  angular: 
    x: 0.0
    y: 0.0
    z: 0.0
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0
children_names: 
  - yawlink
  - pitchendlink
  - maininsertionlink
  - toolrolllink
  - toolpitchlink
  - toolyawlink
  - toolgripper1link
  - toolgripper2link
joint_names: 
  - baselink-yawlink
  - yawlink-pitchbacklink
  - pitchendlink-maininsertionlink
  - maininsertionlink-toolrolllink
  - toolrolllink-toolpitchlink
  - toolpitchlink-toolyawlink
  - toolyawlink-toolgripper1link
  - toolyawlink-toolgripper2link
joint_positions: [0.9393908977508545, -0.8615641593933105, -5.45608600077685e-06, -1.966925859451294, -1.5729533433914185, -0.007319674827158451, 0.4990171790122986, 0.49937185645103455]
joint_velocities: [1.3964370737085119e-05, 2.0839886929024942e-05, -1.2431911056154377e-09, 0.0006299652741290629, 3.368239021028785e-09, -5.1885272114304826e-05, 5.933540325742115e-09, -4.502302530795532e-08]
joint_efforts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 40795
  stamp: 
    secs: 1645168990
    nsecs: 279104948
  frame_id: ''
sim_step: 56650
name: 
  data: "baselink"
wall_time: 472.1219787597656
sim_time: 472.0833435058594
mass: 0.0
pInertia: 
  x: 0.0
  y: 0.0
  z: 0.0
pose: 
  position: 
    x: 0.9999999999999999
    y: 1.3461
    z: 1.3499
  orientation: 
    x: -0.24321186724195806
    y: -0.33035197102490294
    z: -0.9076783411704369
    w: 0.08851887845389675
twist: 
  linear: 
    x: 0.0
    y: 0.0
    z: 0.0
  angular: 
    x: 0.0
    y: 0.0
    z: 0.0
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0
children_names: 
  - yawlink
  - pitchendlink
  - maininsertionlink
  - toolrolllink
  - toolpitchlink
  - toolyawlink
  - toolgripper1link
  - toolgripper2link
joint_names: 
  - baselink-yawlink
  - yawlink-pitchbacklink
  - pitchendlink-maininsertionlink
  - maininsertionlink-toolrolllink
  - toolrolllink-toolpitchlink
  - toolpitchlink-toolyawlink
  - toolyawlink-toolgripper1link
  - toolyawlink-toolgripper2link
joint_positions: [0.939391016960144, -0.8615639805793762, -5.456099188450025e-06, -1.966919183731079, -1.5729533433914185, -0.007320745382457972, 0.4990171790122986, 0.49937185645103455]
joint_velocities: [1.5708672435721382e-05, 2.3443142708856612e-05, -1.5891539195678206e-09, 0.0008038166561163962, 3.5640823625726625e-09, -0.00012850867642555386, 6.134739383156784e-09, -4.673779230301989e-08]
joint_efforts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 40796
  stamp: 
    secs: 1645168990
    nsecs: 286629200
  frame_id: ''
sim_step: 56651
name: 
  data: "baselink"
wall_time: 472.13031005859375
sim_time: 472.0916748046875
mass: 0.0
pInertia: 
  x: 0.0
  y: 0.0
  z: 0.0
pose: 
  position: 
    x: 0.9999999999999999
    y: 1.3461
    z: 1.3499
  orientation: 
    x: -0.24321186724195806
    y: -0.33035197102490294
    z: -0.9076783411704369
    w: 0.08851887845389675
twist: 
  linear: 
    x: 0.0
    y: 0.0
    z: 0.0
  angular: 
    x: 0.0
    y: 0.0
    z: 0.0
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0
children_names: 
  - yawlink
  - pitchendlink
  - maininsertionlink
  - toolrolllink
  - toolpitchlink
  - toolyawlink
  - toolgripper1link
  - toolgripper2link
joint_names: 
  - baselink-yawlink
  - yawlink-pitchbacklink
  - pitchendlink-maininsertionlink
  - maininsertionlink-toolrolllink
  - toolrolllink-toolpitchlink
  - toolpitchlink-toolyawlink
  - toolyawlink-toolgripper1link
  - toolyawlink-toolgripper2link
joint_positions: [0.9393911361694336, -0.8615638017654419, -5.456112376123201e-06, -1.9669125080108643, -1.5729533433914185, -0.007322179153561592, 0.4990171790122986, 0.49937185645103455]
joint_velocities: [1.3962162483949214e-05, 2.0836811017943546e-05, -1.5741178360784147e-09, 0.0007945550605654716, 2.9545699220534516e-09, -0.00017204192408826202, 4.846789636303583e-09, -3.6809357339961934e-08]
joint_efforts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 40797
  stamp: 
    secs: 1645168990
    nsecs: 295105934
  frame_id: ''
sim_step: 56652
name: 
  data: "baselink"
wall_time: 472.1386413574219
sim_time: 472.1000061035156
mass: 0.0
pInertia: 
  x: 0.0
  y: 0.0
  z: 0.0
pose: 
  position: 
    x: 0.9999999999999999
    y: 1.3461
    z: 1.3499
  orientation: 
    x: -0.24321186724195806
    y: -0.33035197102490294
    z: -0.9076783411704369
    w: 0.08851887845389675
twist: 
  linear: 
    x: 0.0
    y: 0.0
    z: 0.0
  angular: 
    x: 0.0
    y: 0.0
    z: 0.0
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0
children_names: 
  - yawlink
  - pitchendlink
  - maininsertionlink
  - toolrolllink
  - toolpitchlink
  - toolyawlink
  - toolgripper1link
  - toolgripper2link
joint_names: 
  - baselink-yawlink
  - yawlink-pitchbacklink
  - pitchendlink-maininsertionlink
  - maininsertionlink-toolrolllink
  - toolrolllink-toolpitchlink
  - toolpitchlink-toolyawlink
  - toolyawlink-toolgripper1link
  - toolyawlink-toolgripper2link
joint_positions: [0.9393912553787231, -0.8615636229515076, -5.4561269280384295e-06, -1.9669053554534912, -1.5729533433914185, -0.007324026431888342, 0.4990171790122986, 0.49937185645103455]
joint_velocities: [1.3961132026452105e-05, 2.0835364921367727e-05, -1.718230557834488e-09, 0.0008652188116684556, 2.743991700526749e-09, -0.00022166404232848436, 4.681295351360859e-09, -3.4572465779092454e-08]
joint_efforts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 40798
  stamp: 
    secs: 1645168990
    nsecs: 303947687
  frame_id: ''
sim_step: 56653
name: 
  data: "baselink"
wall_time: 472.14697265625
sim_time: 472.10833740234375
mass: 0.0
pInertia: 
  x: 0.0
  y: 0.0
  z: 0.0
pose: 
  position: 
    x: 0.9999999999999999
    y: 1.3461
    z: 1.3499
  orientation: 
    x: -0.24321186724195806
    y: -0.33035197102490294
    z: -0.9076783411704369
    w: 0.08851887845389675
twist: 
  linear: 
    x: 0.0
    y: 0.0
    z: 0.0
  angular: 
    x: 0.0
    y: 0.0
    z: 0.0
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0
children_names: 
  - yawlink
  - pitchendlink
  - maininsertionlink
  - toolrolllink
  - toolpitchlink
  - toolyawlink
  - toolgripper1link
  - toolgripper2link
joint_names: 
  - baselink-yawlink
  - yawlink-pitchbacklink
  - pitchendlink-maininsertionlink
  - maininsertionlink-toolrolllink
  - toolrolllink-toolpitchlink
  - toolpitchlink-toolyawlink
  - toolyawlink-toolgripper1link
  - toolyawlink-toolgripper2link
joint_positions: [0.9393913745880127, -0.8615634441375732, -5.456144208437763e-06, -1.9668965339660645, -1.5729533433914185, -0.007326546125113964, 0.4990171790122986, 0.49937185645103455]
joint_velocities: [1.5705052646808326e-05, 2.343806227145251e-05, -2.0934796118865506e-09, 0.0010517186019569635, 2.823608014068668e-09, -0.0003023649042006582, 4.677545017983675e-09, -3.451616947813818e-08]
joint_efforts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

```
