### DISCUSSION TITLE
Task 1 Camera Frames

### DISCUSSION THREAD

**Discussion by jiang-yiwei** [surgical-robotics-ai/surgical_robotics_challenge#42] [Q&A] [answered]
Hi,

In task 1, can I assume that the offset between the left camera and the right camera is a known constant? 

By looking into the yaml file/subscribing to the topics, I see the transformation is only a 0.04 translation offset in the horizontal direction. In other words, is the optical center of the cameraR always at (0, 0.04, 0) in cameraL's frame?

Thank you so much!

Yiwei

**Comment by adnanmunawar** [comment, marked as answer]
Hello Yiwei,
Yes, the camera offset is going to remain constant throughout the 3 tasks. And that is correct, the `cameraL` is 0.02 Simulation Units left of the `CameraFrame` and `cameraR` is 0.02 Simulation Units right of it in the y-direction.

**Reply by jiang-yiwei** [reply]
Thank you for the confirmation!

**Comment by kschwan** [comment]
Hi guys,
Can I ask a related question --

Are the stereo camera's optical axes supposed to be parallel? They are not currently. Cameras are translated wrt. each other, but they "look at" the same point, i.e., 
```yaml
cameraL:
  location: {x: -0.02, y: 0.0, z: -0.5}
  look at: {x: 0.0, y: 0.0, z: -1.0}
cameraR:
  location: {x: 0.02, y: 0.0, z: -0.5}
  look at: {x: 0.0, y: 0.0, z: -1.0}
```
Visualized:
![image](https://user-images.githubusercontent.com/821793/163449336-58fadc6b-f143-445d-84ea-b14b8688c8ad.png)

Instead using the following parameters, the optical axes become parallel:
```yaml
cameraL:
  location: {x: -0.02, y: 0.0, z: -0.5}
  look at: {x: -0.02, y: 0.0, z: -1.0}
cameraR:
  location: {x: 0.02, y: 0.0, z: -0.5}
  look at: {x: 0.02, y: 0.0, z: -1.0}
```
